### ISSUE TITLE
reading wav file from kaggle data

### ISSUE THREAD

**Issue by maheshwarideepak02** [Ayush-Parhi/SpeechToTextModel#1]
Hey how do you managed to read the wav file i guess it is in compressed format when i downloaded from kaggle and when i tried to import just as you did i am facing error of unknown file format

**Comment by Ayush-Parhi** [comment]
Yes, It is in a compressed format. I manually unzip the file and then started the project. As you can see in the "train_audio_path" variable I stored the path to the "train" folder which is saved when you unzip the training data. Otherwise, you can unzip the file by writing a few lines of code too.
I hope this resolves your issue.

**Comment by Ayush-Parhi** [comment]
Yes, It is in a compressed format. I manually unzipped the file and then started the project. As you can see in the "train_audio_path" variable I stored the path to the "train" folder which is saved when you unzip the training data. Otherwise, you can unzip the file by writing a few lines of code too.
I hope this resolves your issue.

**Comment by maheshwarideepak02** [comment]
actually I unzipped and then tried to read the data then it is showing error ,so to check this I even tried to manually play the wav file it is showing error so how did you managed that

**Comment by maheshwarideepak02** [comment]
and also when I unzipped the data in the train folder I checked out that ineach and every folder there is two types of files wav  one of audio and others showing text

**Comment by maheshwarideepak02** [comment]
it would be of great help if you may give your whatsapp no or email id

**Comment by Ayush-Parhi** [comment]
> actually I unzipped and then tried to read the data then it is showing error ,so to check this I even tried to manually play the wav file it is showing error so how did you managed that

Can you please elaborate on what is the error?

**Comment by maheshwarideepak02** [comment]
yeah sure , I tried using lybrosa library's using the load function  and showing the error unknown data format

**Comment by Ayush-Parhi** [comment]
E-mail me the screenshot of your code @ ayushparhi7@gmail.com

**Comment by maheshwarideepak02** [comment]
I have sent a mail on your given email id
